CREATE TABLE usuario_role
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role       VARCHAR(255)                             NOT NULL,
    usuario_id UUID                                     NOT NULL,
    CONSTRAINT pk_usuario_role PRIMARY KEY (id)
);

ALTER TABLE usuario_role
    ADD CONSTRAINT UNIQUE_USUARIO_ROLE UNIQUE (role, usuario_id);

ALTER TABLE usuario_role
    ADD CONSTRAINT FK_USUARIO_ROLE_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (uuid);